### Restaurant
# @prompt name
# @prompt description
# @prompt image
# @prompt address
# @prompt phone
# @prompt category
# @prompt deliveryFee
# @prompt rating
# @prompt isOpen
# @prompt tags
POST http://localhost:3000/api/restaurant
Content-Type: application/json
Authorization: Bearer 

{
   "name": "{{name}}",
  "description": "{{description}}",
  "image": "{{image}}",
  "address": "{{address}}",
  "phone": "{{phone}}",
  "category": "{{category}}",
  "deliveryFee": "{{deliveryFee}}",
  "rating": "{{rating}}",
  "isOpen": "{{isOpen}}",
  "tags": "{{tags}}"
}

### menu items
# @prompt RestaurantId
# @prompt name
# @prompt price
# @prompt image
# @prompt category
# @prompt isAvailable
POST http://localhost:3000/api/menuItems
Content-Type: application/json
Authorization: Bearer 

{
  "RestaurantId": "{{RestaurantId}}" ,
  "name": "{{name}}",
  "price": "{{price}}",
  "image": "{{image}}",
  "category": "{{category}}",
  "isAvailable": "{{isAvailable}}"
}

### all restaurant admin only
GET http://localhost:3000/api/all
Authorization: Bearer 
### owner restaurant
GET http://localhost:3000/api/myrestaurant
Authorization: Bearer 

### menu of the restaurant
GET http://localhost:3000/api/restaurant/menu
Authorization: Bearer 

###
GET http://localhost:3000/api/restaurant/menuItems/691fefd6f3a8d764e9fdd96b